<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>10&nbsp; Drafting Mini-Project 1 – STA 2310 Data Communication with AI</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-ac731d99f942368ec2047317e7e82b91.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style type="text/css">
.sidebar .chapter-number {
color: #FFB81c;
}
.center-panel.quarto-layout-panel {
justify-content: center;
column-gap: 1rem;
}
</style>
<style>
div.callout-example.callout {
  border-left-color: #008000;
}
div.callout-example.callout-style-default > .callout-header {
  background-color: rgba(0, 128, 0, 0.13);
}
div.callout-example .callout-toggle::before {  background-image: url('data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="rgb(33, 37, 41)" class="bi bi-chevron-down" viewBox="0 0 16 16"><path fill-rule="evenodd" d="M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z"/></svg>');}
div.callout-example.callout-style-default .callout-icon::before, div.callout-example.callout-titled .callout-icon::before {
  content: '📈';
  background-image: none;
}
</style>


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./10.html"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Drafting Mini-Project 1</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./"></a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">What Is Data Communication with AI?</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Audience, Claims, Evidence, and AI Boundaries</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Getting Started with Quarto in RStudio</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Finding and Evaluating Data Sources</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Data Dictionaries and Variable Meaning</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Cleaning for Communication</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Descriptive Summaries</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Context for Comparison</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Planning Mini-Project 1</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Drafting Mini-Project 1</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Reviewing and Revising Mini-Project 1</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#from-proposal-to-draft" id="toc-from-proposal-to-draft" class="nav-link active" data-scroll-target="#from-proposal-to-draft"><span class="header-section-number">10.1</span> From Proposal to Draft</a></li>
  <li><a href="#what-the-draft-should-accomplish" id="toc-what-the-draft-should-accomplish" class="nav-link" data-scroll-target="#what-the-draft-should-accomplish"><span class="header-section-number">10.2</span> What the Draft Should Accomplish</a></li>
  <li><a href="#a-practical-memo-structure" id="toc-a-practical-memo-structure" class="nav-link" data-scroll-target="#a-practical-memo-structure"><span class="header-section-number">10.3</span> A Practical Memo Structure</a></li>
  <li><a href="#write-the-opening-for-the-audience" id="toc-write-the-opening-for-the-audience" class="nav-link" data-scroll-target="#write-the-opening-for-the-audience"><span class="header-section-number">10.4</span> Write the Opening for the Audience</a></li>
  <li><a href="#write-a-compact-source-note" id="toc-write-a-compact-source-note" class="nav-link" data-scroll-target="#write-a-compact-source-note"><span class="header-section-number">10.5</span> Write a Compact Source Note</a></li>
  <li><a href="#choose-the-main-evidence" id="toc-choose-the-main-evidence" class="nav-link" data-scroll-target="#choose-the-main-evidence"><span class="header-section-number">10.6</span> Choose the Main Evidence</a></li>
  <li><a href="#build-a-communication-table" id="toc-build-a-communication-table" class="nav-link" data-scroll-target="#build-a-communication-table"><span class="header-section-number">10.7</span> Build a Communication Table</a></li>
  <li><a href="#interpret-rather-than-transcribe" id="toc-interpret-rather-than-transcribe" class="nav-link" data-scroll-target="#interpret-rather-than-transcribe"><span class="header-section-number">10.8</span> Interpret Rather Than Transcribe</a></li>
  <li><a href="#keep-the-claim-at-the-strength-of-the-evidence" id="toc-keep-the-claim-at-the-strength-of-the-evidence" class="nav-link" data-scroll-target="#keep-the-claim-at-the-strength-of-the-evidence"><span class="header-section-number">10.9</span> Keep the Claim at the Strength of the Evidence</a></li>
  <li><a href="#add-a-specific-limitation" id="toc-add-a-specific-limitation" class="nav-link" data-scroll-target="#add-a-specific-limitation"><span class="header-section-number">10.10</span> Add a Specific Limitation</a></li>
  <li><a href="#document-ai-use" id="toc-document-ai-use" class="nav-link" data-scroll-target="#document-ai-use"><span class="header-section-number">10.11</span> Document AI Use</a></li>
  <li><a href="#draft-the-memo-in-quarto" id="toc-draft-the-memo-in-quarto" class="nav-link" data-scroll-target="#draft-the-memo-in-quarto"><span class="header-section-number">10.12</span> Draft the Memo in Quarto</a></li>
  <li><a href="#revise-while-drafting" id="toc-revise-while-drafting" class="nav-link" data-scroll-target="#revise-while-drafting"><span class="header-section-number">10.13</span> Revise While Drafting</a></li>
  <li><a href="#draft-review-checklist" id="toc-draft-review-checklist" class="nav-link" data-scroll-target="#draft-review-checklist"><span class="header-section-number">10.14</span> Draft Review Checklist</a></li>
  <li><a href="#recap" id="toc-recap" class="nav-link" data-scroll-target="#recap"><span class="header-section-number">10.15</span> Recap</a></li>
  <li><a href="#check-your-understanding" id="toc-check-your-understanding" class="nav-link" data-scroll-target="#check-your-understanding"><span class="header-section-number">10.16</span> Check your understanding</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Drafting Mini-Project 1</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Mini-Project 1 now moves from planning to drafting.</p>
<p>In Chapter 9, you built a proposal packet that connected an audience, a focused question, a source, a draft claim, an evidence plan, a caveat, and an AI-use plan. A proposal helps you decide what the memo should do. A draft begins doing it for a reader.</p>
<p>This chapter focuses on:</p>
<ul>
<li>turning a proposal into a short data memo;</li>
<li>organizing the memo around an audience question;</li>
<li>writing a useful source note;</li>
<li>presenting one focused communication table;</li>
<li>interpreting evidence without repeating every value;</li>
<li>separating description from explanation and causation;</li>
<li>writing a specific limitation;</li>
<li>documenting AI use;</li>
<li>drafting and rendering the memo in Quarto.</li>
</ul>
<div class="callout callout-style-default callout-note callout-titled" title="A draft is not a finished memo">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>A draft is not a finished memo
</div>
</div>
<div class="callout-body-container callout-body">
<p>The purpose of a draft is to make your thinking visible enough to test. A useful draft may still need revision, but it should contain the major pieces of the memo so that feedback can address the argument, evidence, and communication choices.</p>
</div>
</div>
<section id="from-proposal-to-draft" class="level2" data-number="10.1">
<h2 data-number="10.1" class="anchored" data-anchor-id="from-proposal-to-draft"><span class="header-section-number">10.1</span> From Proposal to Draft</h2>
<p>A proposal is written mainly for the writer. It records decisions that guide the project. A memo is written for the audience. It turns those decisions into a clear path through the evidence.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Proposal Piece</th>
<th>Draft Memo Job</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Audience</td>
<td>Sets the language, detail, and context.</td>
</tr>
<tr class="even">
<td>Focused question</td>
<td>Gives the memo a purpose.</td>
</tr>
<tr class="odd">
<td>Source fit</td>
<td>Becomes a brief source note.</td>
</tr>
<tr class="even">
<td>Variables and evidence plan</td>
<td>Produce the main table.</td>
</tr>
<tr class="odd">
<td>Draft claim</td>
<td>Becomes an interpretation supported by the table.</td>
</tr>
<tr class="even">
<td>Caveat</td>
<td>Becomes a specific limitation attached to the claim.</td>
</tr>
<tr class="odd">
<td>AI-use plan</td>
<td>Becomes documentation of what AI actually did and how its output was checked.</td>
</tr>
</tbody>
</table>
<p>The proposal does not need to appear as a separate section in the memo. Its pieces should shape what the reader sees.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Turn planning language into reader language">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Turn planning language into reader language
</div>
</div>
<div class="callout-body-container callout-body">
<p>Proposal language often says, “I plan to compare…” Draft language should say what the memo does: “This memo compares…” or “The table shows…”</p>
</div>
</div>
</section>
<section id="what-the-draft-should-accomplish" class="level2" data-number="10.2">
<h2 data-number="10.2" class="anchored" data-anchor-id="what-the-draft-should-accomplish"><span class="header-section-number">10.2</span> What the Draft Should Accomplish</h2>
<p>The Mini-Project 1 draft should allow a reader to answer five questions:</p>
<ol type="1">
<li>What question is this memo answering?</li>
<li>What source and observations are being summarized?</li>
<li>What does the main table show?</li>
<li>What conclusion is supported by that evidence?</li>
<li>What important limit should affect the interpretation?</li>
</ol>
<p>A short memo does not need to include everything you learned while working. It needs to include what the audience needs in order to understand and evaluate the main claim.</p>
</section>
<section id="a-practical-memo-structure" class="level2" data-number="10.3">
<h2 data-number="10.3" class="anchored" data-anchor-id="a-practical-memo-structure"><span class="header-section-number">10.3</span> A Practical Memo Structure</h2>
<p>One useful structure is:</p>
<ol type="1">
<li><strong>Title</strong>: Names the subject and, when useful, the comparison or time period.</li>
<li><strong>Opening</strong>: Identifies the audience question and previews the main finding.</li>
<li><strong>Source note</strong>: Explains where the data came from, what one row represents, and any important preparation decisions.</li>
<li><strong>Main table</strong>: Presents the evidence needed to answer the question.</li>
<li><strong>Interpretation</strong>: Explains the pattern, comparison, or magnitude in plain language.</li>
<li><strong>Limitation</strong>: States what the evidence does not measure or prove.</li>
<li><strong>AI-use note</strong>: Documents any AI assistance and verification.</li>
</ol>
<p>These pieces do not need to be equally long. In a short memo, the opening and source note may each be one paragraph. The table and interpretation should receive the most attention because they carry the evidence.</p>
<div class="callout callout-style-simple callout-example callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Example</span>Example 10.1: Draft structure
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Title:</strong> Recorded Grades by Tutoring-Use Group, Spring 2027</p>
<p><strong>Opening:</strong> This memo summarizes recorded final grades for students in the cleaned Spring 2027 tutoring file. It compares students with at least one completed tutoring visit with students who had no recorded completed visit.</p>
<p><strong>Source note:</strong> The analysis combines appointment records with course-grade records. The final summary uses one row per student and includes only records that could be matched with an anonymous student key.</p>
<p><strong>Main table:</strong> A table showing the number of students, number with recorded grades, average grade, and median grade for each tutoring-use group.</p>
<p><strong>Interpretation:</strong> Students with at least one completed visit had a higher average recorded grade in this file. The group sizes and medians provide context for that difference.</p>
<p><strong>Limitation:</strong> This descriptive comparison does not show that tutoring caused the grade difference. The groups may differ in motivation, prior preparation, course enrollment, or other ways not measured here.</p>
</div>
</div>
</section>
<section id="write-the-opening-for-the-audience" class="level2" data-number="10.4">
<h2 data-number="10.4" class="anchored" data-anchor-id="write-the-opening-for-the-audience"><span class="header-section-number">10.4</span> Write the Opening for the Audience</h2>
<p>The opening should quickly establish the purpose of the memo. A useful opening usually names the audience or decision context, the focused question, the population or time period, and the main finding if the evidence is ready.</p>
<p>Weak opening:</p>
<blockquote class="blockquote">
<p>Tutoring is an important part of college education. Many students use tutoring for many reasons. This paper will discuss tutoring data.</p>
</blockquote>
<p>The opening is broad and delays the actual question.</p>
<p>Stronger opening:</p>
<blockquote class="blockquote">
<p>To help the tutoring center director understand recorded outcomes for Spring 2027, this memo compares final grades for students with at least one completed tutoring visit and students with no recorded completed visit. In the cleaned file, the tutoring-use group had a higher average recorded grade, although the comparison is descriptive rather than causal.</p>
</blockquote>
<p>The stronger version tells the reader what was compared, for whom, when, and how cautiously to read the result.</p>
</section>
<section id="write-a-compact-source-note" class="level2" data-number="10.5">
<h2 data-number="10.5" class="anchored" data-anchor-id="write-a-compact-source-note"><span class="header-section-number">10.5</span> Write a Compact Source Note</h2>
<p>A <strong>source note</strong> gives the reader enough information to understand what the evidence represents. It is not a complete data-management log.</p>
<p>A useful source note may include:</p>
<ul>
<li>the source name or owner;</li>
<li>the file, website, or system from which the data came;</li>
<li>the covered time period;</li>
<li>the unit of observation in the original source;</li>
<li>the unit used in the final table;</li>
<li>important filters, joins, recodes, or exclusions;</li>
<li>how missing values affected the summary.</li>
</ul>
<p>Example:</p>
<blockquote class="blockquote">
<p>The analysis uses a Spring 2027 tutoring appointment export and a course-grade file. The appointment export contains one row per appointment, but the final table summarizes unique students. Canceled and no-show appointments were not counted as completed visits. Records without a matching anonymous student key were excluded from the joined analysis, and missing final grades were excluded from grade calculations but retained in the reported group counts.</p>
</blockquote>
<div class="callout callout-style-default callout-warning callout-titled" title="Do not hide the unit of observation">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Do not hide the unit of observation
</div>
</div>
<div class="callout-body-container callout-body">
<p>If the source has one row per appointment but the claim concerns students, the memo must explain how appointments became a student-level summary. Counting rows and counting people are not the same operation.</p>
</div>
</div>
</section>
<section id="choose-the-main-evidence" class="level2" data-number="10.6">
<h2 data-number="10.6" class="anchored" data-anchor-id="choose-the-main-evidence"><span class="header-section-number">10.6</span> Choose the Main Evidence</h2>
<p>The draft should be organized around one main table that directly answers the focused question. Before creating it, complete this sentence:</p>
<blockquote class="blockquote">
<p>If the audience sees only one table, it should show __________ because __________.</p>
</blockquote>
<p>For example:</p>
<blockquote class="blockquote">
<p>If the tutoring center director sees only one table, it should show group size, recorded-grade count, average grade, and median grade by tutoring-use group because those values answer the comparison question and reveal how much evidence is behind each summary.</p>
</blockquote>
<p>Choose columns because they help the audience interpret the claim, not simply because they are available.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Useful Column</th>
<th>Why It May Matter</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Group label</td>
<td>Defines the comparison.</td>
</tr>
<tr class="even">
<td>Total group size</td>
<td>Shows how many units are represented.</td>
</tr>
<tr class="odd">
<td>Valid-value count</td>
<td>Shows how many observations contribute to a statistic.</td>
</tr>
<tr class="even">
<td>Count or percentage</td>
<td>Answers a frequency question.</td>
</tr>
<tr class="odd">
<td>Mean or median</td>
<td>Summarizes the center of a numeric variable.</td>
</tr>
<tr class="even">
<td>Difference</td>
<td>Makes the comparison explicit.</td>
</tr>
<tr class="odd">
<td>Time period or benchmark</td>
<td>Provides context for interpretation.</td>
</tr>
</tbody>
</table>
<p>More columns do not automatically create more evidence. Extra columns can bury the answer.</p>
</section>
<section id="build-a-communication-table" class="level2" data-number="10.7">
<h2 data-number="10.7" class="anchored" data-anchor-id="build-a-communication-table"><span class="header-section-number">10.7</span> Build a Communication Table</h2>
<p>An analysis table helps the analyst inspect results. A <strong>communication table</strong> helps an audience understand the result. It should have a descriptive title, readable labels, visible units, sensible rounding, group sizes or denominators, and a note when exclusions or definitions matter.</p>
<p>Analysis output:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>tut_grp</th>
<th style="text-align: right;">n</th>
<th style="text-align: right;">n_grade</th>
<th style="text-align: right;">avg_fg</th>
<th style="text-align: right;">med_fg</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0</td>
<td style="text-align: right;">184</td>
<td style="text-align: right;">169</td>
<td style="text-align: right;">76.43846</td>
<td style="text-align: right;">78</td>
</tr>
<tr class="even">
<td>1</td>
<td style="text-align: right;">72</td>
<td style="text-align: right;">68</td>
<td style="text-align: right;">82.17647</td>
<td style="text-align: right;">84</td>
</tr>
</tbody>
</table>
<p>Communication table:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 15%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th>Tutoring-use group</th>
<th style="text-align: right;">Students</th>
<th style="text-align: right;">Students with recorded grades</th>
<th style="text-align: right;">Average final grade</th>
<th style="text-align: right;">Median final grade</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>No completed visit recorded</td>
<td style="text-align: right;">184</td>
<td style="text-align: right;">169</td>
<td style="text-align: right;">76.4</td>
<td style="text-align: right;">78</td>
</tr>
<tr class="even">
<td>At least one completed visit</td>
<td style="text-align: right;">72</td>
<td style="text-align: right;">68</td>
<td style="text-align: right;">82.2</td>
<td style="text-align: right;">84</td>
</tr>
</tbody>
</table>
<p>Table note:</p>
<blockquote class="blockquote">
<p>Completed visits exclude canceled and no-show appointments. Grade summaries exclude missing final grades.</p>
</blockquote>
<p>The second table contains the same main statistics, but its labels, rounding, and note make the evidence easier to interpret.</p>
</section>
<section id="interpret-rather-than-transcribe" class="level2" data-number="10.8">
<h2 data-number="10.8" class="anchored" data-anchor-id="interpret-rather-than-transcribe"><span class="header-section-number">10.8</span> Interpret Rather Than Transcribe</h2>
<p>The interpretation should tell the reader what matters in the table. It should not narrate every cell.</p>
<p>Weak interpretation:</p>
<blockquote class="blockquote">
<p>There were 184 students in the first group and 72 in the second group. The first average was 76.4 and the second average was 82.2. The medians were 78 and 84.</p>
</blockquote>
<p>Stronger interpretation:</p>
<blockquote class="blockquote">
<p>Students with at least one completed tutoring visit had an average recorded final grade of 82.2, compared with 76.4 among students with no recorded completed visit, a difference of 5.8 points. The median showed a similar pattern. The tutoring-use group was smaller, and four of its 72 students had missing final grades; the comparison therefore describes the available records rather than all possible student outcomes.</p>
</blockquote>
<p>The stronger paragraph identifies the comparison, quantifies the difference, uses a second statistic as context, and explains a relevant limitation.</p>
</section>
<section id="keep-the-claim-at-the-strength-of-the-evidence" class="level2" data-number="10.9">
<h2 data-number="10.9" class="anchored" data-anchor-id="keep-the-claim-at-the-strength-of-the-evidence"><span class="header-section-number">10.9</span> Keep the Claim at the Strength of the Evidence</h2>
<p>A descriptive table can support descriptive and comparative statements.</p>
<p>Supported:</p>
<blockquote class="blockquote">
<p>In the cleaned file, the average recorded grade was 5.8 points higher in the tutoring-use group.</p>
</blockquote>
<p>Not supported by the table alone:</p>
<blockquote class="blockquote">
<p>Tutoring raised student grades by 5.8 points.</p>
</blockquote>
<p>The second statement is causal. It assumes the groups would otherwise have had the same outcomes. A simple comparison does not establish that assumption.</p>
<p>Words such as <em>caused</em>, <em>led to</em>, <em>resulted in</em>, <em>improved</em>, and <em>because of</em> often signal causal overstatement. Descriptive alternatives include <em>was higher than</em>, <em>differed by</em>, <em>was associated with</em>, <em>was observed among</em>, and <em>in this file</em>.</p>
</section>
<section id="add-a-specific-limitation" class="level2" data-number="10.10">
<h2 data-number="10.10" class="anchored" data-anchor-id="add-a-specific-limitation"><span class="header-section-number">10.10</span> Add a Specific Limitation</h2>
<p>A limitation is useful when it changes how the audience should interpret the result.</p>
<p>Weak limitation:</p>
<blockquote class="blockquote">
<p>The data may have some problems.</p>
</blockquote>
<p>Stronger limitation:</p>
<blockquote class="blockquote">
<p>The comparison includes only students with recorded final grades and does not account for prior preparation, course difficulty, motivation, or other differences between the groups. It should not be interpreted as an estimate of the effect of tutoring.</p>
</blockquote>
<p>A specific limitation names the limited feature, explains the consequence for interpretation, and identifies any claim the reader should avoid. It belongs near the claim it qualifies.</p>
</section>
<section id="document-ai-use" class="level2" data-number="10.11">
<h2 data-number="10.11" class="anchored" data-anchor-id="document-ai-use"><span class="header-section-number">10.11</span> Document AI Use</h2>
<p>The draft should report what AI actually did, not what you originally planned for it to do.</p>
<p>Useful AI-use note:</p>
<blockquote class="blockquote">
<p>AI was used to suggest revisions to the interpretation paragraph and to identify possible causal wording. I checked every numerical value against the rendered R output and made the final wording decisions. AI was not used to generate or replace data.</p>
</blockquote>
<p>Another useful note:</p>
<blockquote class="blockquote">
<p>AI helped troubleshoot a Quarto table-formatting error. I tested the revised code, inspected the rendered table, and verified its values against the unformatted summary.</p>
</blockquote>
<p>A useful note identifies the task, the verification step, and any meaningful boundary.</p>
<div class="callout callout-style-default callout-note callout-titled" title="AI assistance does not transfer responsibility">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>AI assistance does not transfer responsibility
</div>
</div>
<div class="callout-body-container callout-body">
<p>The author remains responsible for the source description, code, values, interpretation, citations, and final wording. A fluent AI response is not evidence that a result is correct.</p>
</div>
</div>
</section>
<section id="draft-the-memo-in-quarto" class="level2" data-number="10.12">
<h2 data-number="10.12" class="anchored" data-anchor-id="draft-the-memo-in-quarto"><span class="header-section-number">10.12</span> Draft the Memo in Quarto</h2>
<p>A simple draft can use this structure:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Recorded Grades by Tutoring-Use Group"</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> "Your Name"</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span><span class="co"> docx</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">## Purpose and Main Finding</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">State the audience question and preview the main finding.</span><span class="co">]</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="fu">## Data Source</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">Name the source, time period, unit of observation, important cleaning decisions, and missing-value treatment.</span><span class="co">]</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="fu">## Main Evidence</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">Include one communication table and interpret its main comparison.</span><span class="co">]</span></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a><span class="fu">## Limitation</span></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">State one specific limit and explain its consequence for the claim.</span><span class="co">]</span></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a><span class="fu">## AI-Use Note</span></span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">Explain what AI did and how its output was verified.</span><span class="co">]</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Inside an R code cell, table-formatting code might look like this:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: tbl-grade-summary</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="co">#| tbl-cap: "Recorded final grades by tutoring-use group"</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>grade_summary <span class="sc">|&gt;</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>(</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">col.names =</span> <span class="fu">c</span>(</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>      <span class="st">"Tutoring-use group"</span>, <span class="st">"Students"</span>,</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>      <span class="st">"Students with recorded grades"</span>,</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>      <span class="st">"Average final grade"</span>, <span class="st">"Median final grade"</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">digits =</span> <span class="dv">1</span>,</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">align =</span> <span class="fu">c</span>(<span class="st">"l"</span>, <span class="st">"r"</span>, <span class="st">"r"</span>, <span class="st">"r"</span>, <span class="st">"r"</span>)</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>The object <code>grade_summary</code> must already contain checked summary values. Formatting code changes presentation; it should not silently change the analysis.</p>
<p>For a small table with values verified elsewhere, Markdown is also acceptable. Whichever method you use, inspect the rendered output. A table that looks correct in source code may wrap, overflow, lose a note, or become difficult to read after rendering.</p>
</section>
<section id="revise-while-drafting" class="level2" data-number="10.13">
<h2 data-number="10.13" class="anchored" data-anchor-id="revise-while-drafting"><span class="header-section-number">10.13</span> Revise While Drafting</h2>
<p>Drafting may reveal a problem in the proposal. That is useful information.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Drafting Discovery</th>
<th>Responsible Revision</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>The source does not contain the needed measure.</td>
<td>Revise the question or choose a better-supported measure.</td>
</tr>
<tr class="even">
<td>A group has very few observations.</td>
<td>Report the group size and narrow the claim.</td>
</tr>
<tr class="odd">
<td>Many values are missing.</td>
<td>Show valid-value counts and explain the effect on interpretation.</td>
</tr>
<tr class="even">
<td>The planned table does not answer the question.</td>
<td>Redesign the table or revise the question.</td>
</tr>
<tr class="odd">
<td>The draft claim is stronger than the design.</td>
<td>Rewrite it as descriptive or comparative.</td>
</tr>
<tr class="even">
<td>AI-suggested code produces unexpected values.</td>
<td>Inspect intermediate steps and verify definitions and counts.</td>
</tr>
</tbody>
</table>
<p>Revision is not evidence that the plan failed. It is part of responsible analysis.</p>
</section>
<section id="draft-review-checklist" class="level2" data-number="10.14">
<h2 data-number="10.14" class="anchored" data-anchor-id="draft-review-checklist"><span class="header-section-number">10.14</span> Draft Review Checklist</h2>
<p>Before submitting the Mini-Project 1 draft, check that:</p>
<ul>
<li>the opening names a focused purpose and fits a realistic audience;</li>
<li>the source, time period, and unit of observation are clear;</li>
<li>important filters, joins, recodes, exclusions, and missing values are documented;</li>
<li>one main table directly answers the question;</li>
<li>labels, units, group sizes, denominators, and rounding are clear;</li>
<li>every displayed number has been checked;</li>
<li>the interpretation explains the main pattern rather than repeating every cell;</li>
<li>the claim is no stronger than the evidence;</li>
<li>a specific limitation appears near the claim;</li>
<li>the <code>.qmd</code> file renders successfully and the output is readable;</li>
<li>AI assistance and verification are documented.</li>
</ul>
</section>
<section id="recap" class="level2" data-number="10.15">
<h2 data-number="10.15" class="anchored" data-anchor-id="recap"><span class="header-section-number">10.15</span> Recap</h2>
<div class="recap-table">
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th><strong>Keyword</strong></th>
<th><strong>Definition</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Draft memo</strong></td>
<td>A reader-facing version of the project containing the major argument, evidence, interpretation, and limitation.</td>
</tr>
<tr class="even">
<td><strong>Opening</strong></td>
<td>The beginning of the memo that establishes the audience question, context, and main finding.</td>
</tr>
<tr class="odd">
<td><strong>Source note</strong></td>
<td>A compact explanation of where the data came from, what the observations represent, and which preparation decisions matter.</td>
</tr>
<tr class="even">
<td><strong>Unit of observation</strong></td>
<td>What one row or record represents at a particular stage of the analysis.</td>
</tr>
<tr class="odd">
<td><strong>Main evidence</strong></td>
<td>The focused summary that directly supports the memo’s claim.</td>
</tr>
<tr class="even">
<td><strong>Communication table</strong></td>
<td>A table designed for an audience, with readable labels, units, rounding, denominators, and relevant notes.</td>
</tr>
<tr class="odd">
<td><strong>Interpretation</strong></td>
<td>A plain-language explanation of the important pattern, comparison, or magnitude in the evidence.</td>
</tr>
<tr class="even">
<td><strong>Causal overstatement</strong></td>
<td>Language claiming one factor produced an outcome when the design supports only description, comparison, or association.</td>
</tr>
<tr class="odd">
<td><strong>Limitation</strong></td>
<td>A specific condition affecting what the evidence measures, represents, or proves.</td>
</tr>
<tr class="even">
<td><strong>AI-use note</strong></td>
<td>Documentation of what AI did, how its output was checked, and what responsibility remained with the author.</td>
</tr>
<tr class="odd">
<td><strong>Rendered output</strong></td>
<td>The HTML, PDF, or Word document produced from the Quarto source and inspected before submission.</td>
</tr>
</tbody>
</table>
</div>
</section>
<section id="check-your-understanding" class="level2" data-number="10.16">
<h2 data-number="10.16" class="anchored" data-anchor-id="check-your-understanding"><span class="header-section-number">10.16</span> Check your understanding</h2>
<div class="callout callout-style-default callout-note callout-titled" title="Problems">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="true" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Problems
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse show">
<div class="callout-body-container callout-body">
<ol type="1">
<li><p>What is the main difference between a proposal packet and a draft memo?</p></li>
<li><p>Name five pieces that should appear in the Mini-Project 1 draft.</p></li>
<li><p>Why should the opening name the focused audience question?</p></li>
<li><p>What information should a useful source note include?</p></li>
<li><p>Why is one strong main table usually better than several weakly connected tables in this project?</p></li>
<li><p>Rewrite this claim so that it matches descriptive evidence: “Tutoring made students earn higher grades.”</p></li>
<li><p>What is wrong with the limitation “The data might have problems”?</p></li>
<li><p>Why should group sizes, denominators, or valid-value counts appear with percentages, rates, averages, or comparisons?</p></li>
<li><p>Give an example of a useful AI-use note for a draft memo.</p></li>
<li><p>Match each term to the best description:</p></li>
</ol>
<ol type="a">
<li><p>Source note</p></li>
<li><p>Communication table</p></li>
<li><p>Interpretation</p></li>
<li><p>Limitation</p></li>
</ol>
<p>Descriptions:</p>
<ol type="1">
<li><p>A table prepared with readable labels, units, rounding, and relevant context for an audience.</p></li>
<li><p>A specific condition that affects what the evidence represents or proves.</p></li>
<li><p>A compact explanation of the data source, observations, and important preparation decisions.</p></li>
<li><p>A plain-language explanation of the important pattern or comparison in the evidence.</p></li>
</ol>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Solutions">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Solutions
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li><p>A proposal packet records planning decisions for the writer. A draft memo turns those decisions into a reader-facing product with evidence, interpretation, and a limitation.</p></li>
<li><p>Appropriate pieces include a title, opening, source note, main table, interpretation, limitation, and AI-use note. Any five satisfy the question.</p></li>
<li><p>Naming the focused audience question tells the reader what the memo is trying to answer and why the evidence that follows is relevant.</p></li>
<li><p>A useful source note may include the source name or owner, file or system, time period, original and final units of observation, important filters or cleaning decisions, and missing-value treatment.</p></li>
<li><p>One strong table keeps the memo focused on the audience question and makes the relationship between evidence and claim easier to evaluate. Several loosely connected tables can bury the answer.</p></li>
<li><p>One responsible rewrite is: “In the cleaned Spring 2027 file, students with at least one completed tutoring visit had higher average recorded final grades than students with no recorded completed visit.” The memo should also state that the comparison does not establish causation.</p></li>
<li><p>It is too general to help the reader. A useful limitation identifies the specific issue, such as missing grades or unmeasured group differences, and explains how it affects the claim.</p></li>
<li><p>These counts show how much evidence is behind a statistic, clarify who is included, and can reveal missingness or small groups that should affect interpretation.</p></li>
<li><p>One useful note is: “AI was used to suggest revisions to the interpretation paragraph and flag possible causal wording. I checked all numerical values against the rendered R output and made the final wording decisions.”</p></li>
<li><p>a-3. b-1. c-4. d-2.</p></li>
</ol>
</div>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>